# Generated by app/configure_hq.ps1 on the host.
# Update this module by running: .\app\configure_hq.ps1
# Selected VM: HQ-DC01

$script:HqDiskMetadataConfig = [pscustomobject]@{
    AvailableVmNames = @(
        'HQ-DC01'
    )
    SelectedVmName = 'HQ-DC01'

    RoleDefinitions = @(
        [pscustomobject]@{
            VmName = 'HQ-DC01'
            SourceVhd = 'M:\repository1.vhdx'
            VhdName = 'repository1.vhdx'
            RoleName = 'Repository'
            ExpectedDriveLetter = 'R'
            DedupEnabled = $false
        }
    )

    RoleAclDefinitions = @(
        [pscustomobject]@{
            RoleName = 'Repository'
            ManagedPathName = 'repo'
            Principal = 'HQ\Repo_R'
            AccessLevel = 'ReadAndExecute'
            ServiceAccount = 'HQ\svc_repo'
            ServiceAccessLevel = 'FullControl'
        }
    )

    SecurityPrincipalDefinitions = @(
        [pscustomobject]@{
            Principal = 'HQ\Repo_R'
            Type = 'Group'
            ExpectedMemberOf = $null
            PasswordPromptRequired = $false
        }

        [pscustomobject]@{
            Principal = 'HQ\repo_user'
            Type = 'User'
            ExpectedMemberOf = 'HQ\Repo_R'
            PasswordPromptRequired = $true
        }
    )
}

function Get-HqDiskMetadataConfig {
    [CmdletBinding()]
    param()

    return $script:HqDiskMetadataConfig
}

function Get-HqDiskRoleDefinitions {
    [CmdletBinding()]
    param()

    return @($script:HqDiskMetadataConfig.RoleDefinitions)
}

function Get-HqRoleAclMetadataDefinitions {
    [CmdletBinding()]
    param()

    return @($script:HqDiskMetadataConfig.RoleAclDefinitions)
}

function Get-HqSecurityPrincipalMetadataDefinitions {
    [CmdletBinding()]
    param()

    return @($script:HqDiskMetadataConfig.SecurityPrincipalDefinitions)
}

Export-ModuleMember -Function Get-HqDiskMetadataConfig, Get-HqDiskRoleDefinitions, Get-HqRoleAclMetadataDefinitions, Get-HqSecurityPrincipalMetadataDefinitions
