# Generated by app/configure_hq.ps1 on the host.
# Update this module by running: .\app\configure_hq.ps1
# Selected VM: (HQ) alkbio.local

$script:HqDiskMetadataConfig = [pscustomobject]@{
    AvailableVmNames = @(
        '(HQ) alkbio.local'
        '(HQ) SQLDEV -GEN2'
        '(LAB) 0.10 WINDEV'
        '(LAB) 0.2 LABDC'
        '(LAB) 11-4 SQLTRAINING'
        '(LAB) 11-5 SQLPROJECTS'
        '(LAB) 11-6 SQLCLIENTS'
        '(LAB) 12-1 BITRAINING'
        '(LAB) 12-2 BIPROJECTS'
        '(LAB) 12-3 BICLIENTS'
        '(LAB) 13-1 SSRS16'
        '(LAB) 13-2 SSRS17'
        '(LAB) 13-3 SSRS19'
        '(LINUX) BIOLINUX'
        '(LINUX) FEDORA SCIENCE'
        '(LINUX) openSUSE'
        '(MOC) 0.3 MIA-DC (adventureworks.codiz.org) -GEN2 [ADVENTUREWORKS]'
        '(MOC) MIA-SQL'
        '(MOC) MIA-SQLBI'
    )
    SelectedVmName = '(HQ) alkbio.local'

    RoleDefinitions = @(
        [pscustomobject]@{
            VmName = '(HQ) alkbio.local'
            SourceVhd = 'M:\repository1.vhdx'
            VhdName = 'repository1.vhdx'
            RoleName = 'Repository'
            ExpectedDriveLetter = 'R'
            DedupEnabled = $false
        }

        [pscustomobject]@{
            VmName = '(HQ) alkbio.local'
            SourceVhd = 'W:\vmdisk.vhdx'
            VhdName = 'vmdisk.vhdx'
            RoleName = 'Lab'
            ExpectedDriveLetter = 'W'
            DedupEnabled = $true
        }

        [pscustomobject]@{
            VmName = '(HQ) alkbio.local'
            SourceVhd = 'X:\backup1.vhdx'
            VhdName = 'backup1.vhdx'
            RoleName = 'Backups'
            ExpectedDriveLetter = 'B'
            DedupEnabled = $false
        }

        [pscustomobject]@{
            VmName = '(HQ) alkbio.local'
            SourceVhd = 'V:\VHDs\disks\sharedisk.vhdx'
            VhdName = 'sharedisk.vhdx'
            RoleName = 'ShareDrive'
            ExpectedDriveLetter = 'Z'
            DedupEnabled = $false
        }
    )

    RoleAclDefinitions = @(
        [pscustomobject]@{
            RoleName = 'Lab'
            ManagedPathName = 'Shares\lab'
            Principal = 'HQ\Lab_RW'
            AccessLevel = 'Modify'
            ServiceAccount = 'HQ\svc_lab'
            ServiceAccessLevel = 'FullControl'
        }

        [pscustomobject]@{
            RoleName = 'ShareDrive'
            ManagedPathName = 'Shares\share'
            Principal = 'HQ\ShareDrive_R'
            AccessLevel = 'ReadAndExecute'
            ServiceAccount = 'HQ\svc_lab'
            ServiceAccessLevel = 'FullControl'
        }

        [pscustomobject]@{
            RoleName = 'Repository'
            ManagedPathName = 'Shares\repository'
            Principal = 'HQ\Repository_R'
            AccessLevel = 'ReadAndExecute'
            ServiceAccount = 'HQ\svc_lab'
            ServiceAccessLevel = 'FullControl'
        }

        [pscustomobject]@{
            RoleName = 'Backups'
            ManagedPathName = 'Shares\backup'
            Principal = 'HQ\Backups_RW'
            AccessLevel = 'Modify'
            ServiceAccount = 'HQ\svc_lab'
            ServiceAccessLevel = 'FullControl'
        }
    )

    SecurityPrincipalDefinitions = @(
        [pscustomobject]@{
            Principal = 'HQ\Backups_RW'
            Type = 'Group'
            ExpectedMemberOf = $null
            PasswordPromptRequired = $false
        }

        [pscustomobject]@{
            Principal = 'HQ\hector'
            Type = 'User'
            ExpectedMemberOf = @('HQ\Lab_RW', 'HQ\Repository_R', 'HQ\ShareDrive_R')
            PasswordPromptRequired = $true
        }

        [pscustomobject]@{
            Principal = 'HQ\ShareDrive_R'
            Type = 'Group'
            ExpectedMemberOf = $null
            PasswordPromptRequired = $false
        }

        [pscustomobject]@{
            Principal = 'HQ\Lab_RW'
            Type = 'Group'
            ExpectedMemberOf = $null
            PasswordPromptRequired = $false
        }

        [pscustomobject]@{
            Principal = 'HQ\Repository_R'
            Type = 'Group'
            ExpectedMemberOf = $null
            PasswordPromptRequired = $false
        }

        [pscustomobject]@{
            Principal = 'HQ\svc_lab'
            Type = 'User'
            ExpectedMemberOf = @('HQ\Lab_RW', 'HQ\Repository_R', 'HQ\Backups_RW', 'HQ\ShareDrive_R')
            PasswordPromptRequired = $true
        }

        [pscustomobject]@{
            Principal = 'HQ\Researcher'
            Type = 'User'
            ExpectedMemberOf = @('HQ\Lab_RW', 'HQ\ShareDrive_R')
            PasswordPromptRequired = $true
        }
    )
}

function Get-HqDiskMetadataConfig {
    [CmdletBinding()]
    param()

    return $script:HqDiskMetadataConfig
}

function Get-HqDiskRoleDefinitions {
    [CmdletBinding()]
    param()

    return @($script:HqDiskMetadataConfig.RoleDefinitions)
}

function Get-HqRoleAclMetadataDefinitions {
    [CmdletBinding()]
    param()

    return @($script:HqDiskMetadataConfig.RoleAclDefinitions)
}

function Get-HqSecurityPrincipalMetadataDefinitions {
    [CmdletBinding()]
    param()

    return @($script:HqDiskMetadataConfig.SecurityPrincipalDefinitions)
}

Export-ModuleMember -Function Get-HqDiskMetadataConfig, Get-HqDiskRoleDefinitions, Get-HqRoleAclMetadataDefinitions, Get-HqSecurityPrincipalMetadataDefinitions
